# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locateBivacchi', '0002_auto_20181116_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.IntegerField(default=1234),
        ),
    ]
