# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locateBivacchi', '0003_reservation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_bivacco',
            new_name='bivacco',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_user',
            new_name='user',
        ),
    ]
