# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locateBivacchi', '0004_auto_20181116_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.IntegerField()),
                ('location', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
    ]
