# Generated by Django 2.1.3 on 2018-11-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locateBivacchi', '0005_bar'),
    ]

    operations = [
        migrations.AddField(
            model_name='bivacco',
            name='temp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
