# Generated by Django 2.0.6 on 2018-11-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locateBivacchi', '0006_bivacco_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bivacco',
            old_name='coordinaye_y',
            new_name='coordinate_y',
        ),
        migrations.AddField(
            model_name='bivacco',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bivacco',
            name='name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
